fix: fixing dynamic aspect of integration testing on the voice channel
nuecho/rasa-integration-testing pull request #16
Opened 2020-09-04 16:38 UTC by mbrisebo-perso

- Providing variables within a dictionary associated to the "vars" key
- Sender key is "senderId" instead of "sender"
- Step index is computed ans transmitted among the dynamic variables
- HTTP failures on individual tests no longer ends the whole test session

2020-09-04 16:45 UTC, GuillaumeVoisine commented
Qu'est-ce qui fail ? Les tests d'intégration du projet bidon?

2020-09-04 16:59 UTC, vlavoie requested changes

2020-09-04 16:59 UTC, vlavoie commented on rasa_integration_testing/rest_runner.py
> +SENDER_ID_KEY = "senderId"
Ce champ ne devrait pas changer ici. C'est bâti pour être compatible avec le channel REST de Rasa et `sender` est le bon champ, si on le change ça va briser la compatibilité REST. L'erreur se trouve au niveau de rasa-common qui utilise `senderId` au lieu de `sender`.

2020-09-04 16:59 UTC, vlavoie commented on rasa_integration_testing/rest_runner.py
> +STEP_ID_ENV_VARIABLE = "STEP_ID"
Je ne suis pas chaud à l'idée d'insérer des variables d'environnement spécifique au VoiceXML dans le channel REST. Il y a deux façons de régler ça, soit qu'on crée un Runner pour le VoiceXML ou l'autre solution est d'insérer le STEP_ID dans les templates Jinja dans `rasa-ml-banking-demo` .

2020-09-04 18:05 UTC, mbrisebo-perso commented on rasa_integration_testing/rest_runner.py
> +STEP_ID_ENV_VARIABLE = "STEP_ID"
C'est nettement trop lourd de mettre le STEP_ID dans les templates Jinja.
Un runner spécifique au VXML est nettement plus intéressant, surtout que l'on règlerait par le fait même la question de `SENDER_ID_KEY`

2020-09-04 18:07 UTC, vlavoie commented on rasa_integration_testing/rest_runner.py
> +STEP_ID_ENV_VARIABLE = "STEP_ID"
En effet c'est ce que je pensais aussi. Au moins ça va être propre.

2020-09-04 18:09 UTC, mbrisebo-perso commented on rasa_integration_testing/rest_runner.py
> +STEP_ID_ENV_VARIABLE = "STEP_ID"
C'est le temps de tester mes connaissances Python toutes neuves...

2020-09-09 14:00 UTC, vlavoie approved these changes
LGTM, faut juste rouler le `make format` pour régler le pipeline

2020-09-09 17:02 UTC, merged